language: node_js
cache:
  yarn: true
  directories:
  - node_modules
node_js:
  - '8'
install:
  - yarn install
script:
  - yarn build
  - cat /home/travis/build/gladeye/bento/node_modules/sass-loader/lib/loader.js
  - yarn test
